name: Build Pixel 7a (Lynx) kernel with Halium 13

on:
  push:
    branches:
    - 'main'
    pull_request:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
# repo klónozása
      - name: Check out Droidian-Lynx-port repository
        uses: actions/checkout@v3

# Halium 13 letöltése
      - name: Download Halium 13
        run: |
          git clone https://github.com/Halium/android -b halium-13.0 halium

# Kernel klónozása
      - name: Clone Kernel Source
        run: |
          git clone https://github.com/LineageOS/android_kernel_google_gs201 -b lineage-20 kernel

# patchek alkalmazása
      - name: Apply Halium 13 patches
        run: | 
            cd kernel 
            git am ../halium/patches/halium-13.0*.patch || echo "Patch application failed"

# eszközök telepítése
      - name: Install dependencies
        run: |
            sudo apt update
            sudo apt install -y build-essential gcc-aarch64-linux-gnu bc bison flex libssl-dev

# kernel kunfigurálása
      - name: Configure Kernel
        run: |
            cd kernel
            make ARCH=arm64
CROSS_COMPILE=aarch64.linux-gnu-defconfig

# kernel fordítása
      - name: Build Kernel
        run: |
            cd kernel
            make ARCH=arm64
CROSS_COMPILE=aarch64-linux-gnu- -j$(nproc)

# Kernel Image mentése
      - name: Save Kernel Image
        run: |
            mkdir -p output
            cp kernel/arch/arm64/boot/Image.gz output/

# Artifacts feltöltése 
      - name: Upload kernel build artifacts
        uses: actions/upload-artifact@v3
      - witch: 
            name: kernel-build
            path: output/
